# Generated by Django 3.1.1 on 2020-09-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
